[workspace]
git_only = true
changelog_config = "cliff.toml"
dependencies_update = true # update dependencies with `cargo update`
git_release_enable = true # enable GitHub/Gitea releases
semver_check = false # disable API breaking changes checks
publish = false # disable `cargo publish`
git_tag_name = "{{ version }}"
git_release_name = "{{ version }}"
